name: Translate README

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
      - name: Adding README - Español
        uses: dephraiim/translate-readme@main
        with:
          LANG: es